# generated: 2025-05-18T12:05:00Z (auto)
# Default configuration (Spec-complete, with inline comments)

sensor:
  name: Sony IMX273                # Sensor model name
  adc_bits: 10                     # ADC bit depth
  lsb_shift: 6                     # Bit shift applied before saving

environment:
  note: |
    LED : 940 nm CW
    Lens: LH2601A (IR‑pass)
    Temp: 25 °C

measurement:
  gains:                           # dB → sub‑folder
    0:   { folder: gain_0dB }
    6:   { folder: gain_6dB }
    12:  { folder: gain_12dB }
    24:  { folder: gain_24dB }
  exposures:                       # ratio → sub‑folder
    4.0:    { folder: chart_x4 }
    2.0:    { folder: chart_x2 }
    1.0:    { folder: chart_x1 }
    0.5:    { folder: chart_x0.5 }
    0.25:   { folder: chart_x0.25 }
    0.125:  { folder: chart_x0.125 }
    0.0625: { folder: chart_x0.0625 }
  flat_lens_folder: LensFlat       # Flat field with lens
  flat_nolens_folder: flat         # Flat field without lens
  dark_folder: dark                # Dark stacks
  flat_roi_file:  roi/flat.roi     # ROI for flat correction
  chart_roi_file: roi/chart_roi.zip# ROI ZIP for gray chart
  roi_mid_index: 5                 # Mid‑tone patch index 0–10

illumination:
  power_uW_cm2: 67.92              # Incident power
  exposure_ms: 960                 # Base exposure time
  sat_factor: 0.95                 # Saturation threshold (0–1)

processing:
  roi_zip_file: roi/chart_roi.zip  # Default ROI ZIP
  stat_mode: rms                   # rms | mean | median
  snr_threshold_dB: 10             # SNR threshold for DR
  min_sig_factor: 3                # Guard: mean ≥ N×σ
  mask_upper_margin: 0.85          # Use pixels < margin*DN_sat for fitting
  apply_gain_map: false
  plane_fit_order: 2
  read_noise_mode: 0
  prnu_fit: LS
  exclude_abnormal_snr: true

plot:
  # exposures: [4.0,2.0,1.0,0.5,0.25,0.125,0.0625]  # Override order if needed
  color_by_exposure: false         # Optional UI key
  exposure_labels: [3840,1920,960,480,240,120,60]

output:
  output_dir: output
  report_html: true
  report_csv: true
  report_summary: true
  debug_stacks: false
  report_order:
    - Dynamic Range (dB)
    - SNR @ 50% (dB)
    - DN @ 10 dB
    - DN @ 0 dB
    - Read Noise (DN)
    - DSNU (DN)
    - DN_sat
    - PRNU (%)
    - System Sensitivity
