# generated: 2025-05-18T12:05:00Z (auto)
# Default configuration (Spec-complete, with inline comments)

sensor:
  name: Sony IMX273                # Sensor model name
  adc_bits: 10                     # ADC bit depth
  lsb_shift: 6                     # Bit shift applied before saving

environment:
  note: |
    LED : 940 nm CW
    Lens: LH2601A (IR‑pass)
    Temp: 25 °C

measurement:
  gains:                           # dB → sub‑folder
    0:   { folder: gain_0dB }
    6:   { folder: gain_6dB }
    12:  { folder: gain_12dB }
    24:  { folder: gain_24dB }
  exposures:                       # ratio → sub‑folder
    4.0:    { folder: chart_x4 }
    2.0:    { folder: chart_x2 }
    1.0:    { folder: chart_x1 }
    0.5:    { folder: chart_x0.5 }
    0.25:   { folder: chart_x0.25 }
    0.125:  { folder: chart_x0.125 }
    0.0625: { folder: chart_x0.0625 }
  flat_lens_folder: LensFlat       # Flat field with lens
  flat_nolens_folder: flat         # Flat field without lens
  dark_folder: dark                # Dark stacks
  flat_roi_file:  roi/flat.roi     # ROI for flat correction
  chart_roi_file: roi/chart_roi.zip# ROI ZIP for gray chart
  roi_mid_index: 5                 # Mid‑tone patch index 0–10

illumination:
  power_uW_cm2: 67.92              # Incident power
  exposure_ms: 960                 # Base exposure time
  sat_factor: 0.95                 # Saturation threshold (0–1)

processing:
  roi_zip_file: roi/chart_roi.zip  # Default ROI ZIP
  stat_mode: rms                   # rms | mean | median
  snr_threshold_dB: 10             # SNR threshold for DR
  min_sig_factor: 3                # Guard: mean ≥ N×σ
  mask_upper_margin: 0.85          # Use pixels < margin*DN_sat for fitting
  mask_lower_margin: 0.0           # Use pixels >= margin*DN_sat for fitting
  gain_map_mode: none              # self_fit | flat_fit | flat_frame | none
                                  # gain map is scaled by its maximum
  plane_fit_order: 2               # Polynomial order for plane fitting
  gain_fit_method: poly            # poly | rbf | akima | hermite
  fit_subsample_step: 1            # Pixel subsample step for gain fitting
  subsample_method: uniform        # uniform | random sampling mode
  gain_clip_margin: false         # Clip pixels to margins before fitting
  read_noise_mode: 0               # 0: use std of stack, 1: use std of frame diff / √2
  prnu_fit: LS                     # LS or WLS regression method
  exclude_abnormal_snr: true       # Ignore low‑SNR patches

plot:
  # exposures: [4.0,2.0,1.0,0.5,0.25,0.125,0.0625]  # Override order if needed
  color_by_exposure: false         # Optional UI key
  exposure_labels: [3840,1920,960,480,240,120,60]  # Labels for exposure axis
  prnu_squared: false              # Plot μ² vs σ² if true

output:
  output_dir: output               # Root directory for results
  report_html: true                # Generate HTML report
  report_csv: true                 # Generate CSV file
  report_summary: true             # Generate summary text
  debug_stacks: false              # Save intermediate stack images
  report_order:
    - Dynamic Range (dB)
    - SNR @ 50% (dB)
    - DN @ 10 dB
    - DN @ 0 dB
    - Read Noise (DN)
    - Black level (DN)
    - DSNU (DN)
    - DN_sat
    - PRNU (%)
    - System Sensitivity

logging:
  level: INFO                   # DEBUG | INFO | WARNING | ERROR | CRITICAL
